fix: local proxy on node >=18
decentraland/governance pull request #1239
Opened 2023-09-05 18:36 UTC by 2fd

2023-09-06 13:09 UTC, andyesp requested changes

2023-09-06 13:09 UTC, andyesp commented on gatsby-config.js
> +// const { default: developMiddleware } = require('decentraland-gatsby/dist/utils/development/developMiddleware'
Tests are failing without this import

2023-09-15 13:32 UTC, andyesp requested changes

2023-09-15 13:32 UTC, andyesp commented on gatsby-config.js
> +const { default: developMiddleware } = require('decentraland-gatsby/dist/utils/development/developMiddleware'
Missing `)` at the end of the line.

2023-09-18 20:49 UTC, 2fd commented on gatsby-config.js
> +const { default: developMiddleware } = require('decentraland-gatsby/dist/utils/development/developMiddleware'
```suggestion
const { default: developMiddleware } = require('decentraland-gatsby/dist/utils/development/developMiddleware')
```

2023-09-19 15:25 UTC, ncomerci approved these changes

2023-09-19 18:00 UTC, andyesp approved these changes

2023-09-19 19:30 UTC, 1emu approved these changes

2023-09-20 00:12 UTC, merged