Add List of Voters on Proposal Page
decentraland/governance pull request #138
Opened 2021-11-15 01:44 UTC by oliviel

2021-11-15 16:22 UTC, yemel commented
Please include a description about this PR and link it to the corresponding ticket.

2021-11-15 16:44 UTC, yemel commented
### Modify "See Votes" Button
Follow the design attached at the issue: https://github.com/decentraland/governance/issues/135

Do this:
<img width="427" alt="Screen Shot 2021-11-15 at 13 34 58" src="https://user-images.githubusercontent.com/279449/141819340-5ac5c607-bbe7-46fb-ae50-e889c2050da3.png">

Instead of this:
<img width="361" alt="Screen Shot 2021-11-15 at 13 35 05" src="https://user-images.githubusercontent.com/279449/141819354-111931d3-5798-4cd8-ba70-18df2f7d13f7.png">


### Replace the address by Display Name if possible

Do this:
<img width="308" alt="Screen Shot 2021-11-15 at 13 40 52" src="https://user-images.githubusercontent.com/279449/141819983-b12587da-d81c-483a-a0aa-259e3f211494.png">

Instead of this:
<img width="547" alt="Screen Shot 2021-11-15 at 13 40 35" src="https://user-images.githubusercontent.com/279449/141820088-de94f951-3c72-49f8-81ed-1b18c13c8d67.png">

2021-11-15 21:09 UTC, yemel commented
On Voters list, include link to users VP page:

https://governance.decentraland.org/balance/?address=0x37f00ec67d68c2d3c662339c183d37403c36f28e

2021-11-16 16:29 UTC, 2fd requested changes

2021-11-16 16:29 UTC, 2fd commented on src/components/Modal/VotesList.tsx
> +function abbreviateNumber(number: number) {
please move this to `src/entities/Votes/utils.ts`

2021-11-16 16:29 UTC, 2fd commented on src/components/Modal/VotesList.tsx
> +              {/* I added this abbreviateNumber function because when the modal is in mobile screens if the number is high
The explanation of what the function does goes in the function
The explanation of why you added it goes in the PR

🙏

2021-11-16 16:29 UTC, 2fd commented on src/components/Modal/VotesList.tsx
> +    <Header>{Object.entries(votes || {}).length} {Object.entries(votes || {}).length === 1 ? 'Vote' : 'Votes'}</Header>
move this to the `en.json#modal.votes_lis.title` and use `l('modal.votes_lis.title', { votes })`

2021-11-16 17:50 UTC, oliviel commented
> ### Modify "See Votes" Button
> Follow the design attached at the issue: #135
> 
> Do this: <img alt="Screen Shot 2021-11-15 at 13 34 58" width="427" src="https://user-images.githubusercontent.com/279449/141819340-5ac5c607-bbe7-46fb-ae50-e889c2050da3.png">
> 
> Instead of this: <img alt="Screen Shot 2021-11-15 at 13 35 05" width="361" src="https://user-images.githubusercontent.com/279449/141819354-111931d3-5798-4cd8-ba70-18df2f7d13f7.png">
> 
> ### Replace the address by Display Name if possible
> Do this: <img alt="Screen Shot 2021-11-15 at 13 40 52" width="308" src="https://user-images.githubusercontent.com/279449/141819983-b12587da-d81c-483a-a0aa-259e3f211494.png">
> 
> Instead of this: <img alt="Screen Shot 2021-11-15 at 13 40 35" width="547" src="https://user-images.githubusercontent.com/279449/141820088-de94f951-3c72-49f8-81ed-1b18c13c8d67.png">

I change everything here except for the name instead of the address I am facing a problem using the function useAsyncMemo() and profiles.load() is making _rendered more hooks than during the previous render_ I open to suggestions here.

2021-11-16 17:53 UTC, 2fd requested changes

2021-11-16 17:53 UTC, 2fd commented on src/components/Modal/VotesList.tsx
> +    <Header>{Object.entries(votes || {}).length} {Object.entries(votes || {}).length === 1 ? l('modal.votes_list.vote') : l('modal.votes_list.votes')}</Header>
jajaj, I was specting to use a plural definition of intl:

```json5
    // en.json
    {
        "votes": "{votes} {votes, plural, one {Vote} other {Votes}}",
    }
```

and in code:
```jsx
    <Header>{l('modal.votes_list.votes', { votes: Object.keys(votes || {}).length })}</Header>
```

as ref:
https://github.com/decentraland/governance/blob/master/src/intl/en.json#L4

2021-11-17 16:06 UTC, 2fd approved these changes

2021-11-17 16:23 UTC, 2fd requested changes

2021-11-17 16:23 UTC, 2fd commented on src/components/Modal/VotesList.tsx
> +      {Object.entries(votes || {}).sort((a, b) => b[1].vp - a[1].vp).map(vote => {
to load profiles names:
- save the resulte of `Object.entries(votes || {}).sort((a, b) => b[1].vp - a[1].vp)` using a `useMemo`
- create a new component `<VoteListItem key={key} address={key} value={value} />`
- use the `useAsynMemo` hook inside each `VoteListItem` to load the avatar info and show the name

2021-11-17 16:24 UTC, 2fd commented on src/components/Modal/VotesList.tsx
> +      {Object.entries(votes || {}).sort((a, b) => b[1].vp - a[1].vp).map(vote => {
this could help @oliviel

2021-11-18 17:10 UTC, 2fd requested changes

2021-11-18 17:10 UTC, 2fd commented on src/components/Section/ProposalResultSection.tsx
> +        {Object.keys(votes || {}).length > 0 && <Anchor style={{ marginBottom: '5px', textTransform: 'uppercase' }} onClick={onOpenVotesList} >
- cache the result of `Object.keys(votes || {}).length` using a `useMemo`
- use `font-size: 13px`
- move the css into the css file

2021-11-18 17:10 UTC, 2fd commented on src/components/Modal/VotesList.css
> +  max-height: calc(70vh);
```suggestion
  max-height: calc(70vh);
```
```suggestion
  height: 50vh;
```

2021-11-18 17:10 UTC, 2fd commented on src/components/Modal/VotesList.css
> +  overflow-y: scroll;
```suggestion
  overflow-y: scroll;
```
```suggestion
  overflow-y: auto;
```

2021-11-18 17:12 UTC, 2fd commented
Instead of hiding  `see votes` y prefer to show it as disable

<img width="299" alt="Screen Shot 2021-11-18 at 11 07 31" src="https://user-images.githubusercontent.com/208789/142463401-ecc5390f-00b2-4341-a198-a66df51b5659.png">

@yemel WDYT?

2021-11-18 18:40 UTC, yemel commented
Generally, I like better the option of disabling the action button when data is not available.
But since the UI already has a lot of info I think it's ok to hide it.

2021-11-19 18:31 UTC, 2fd approved these changes

2021-11-19 18:32 UTC, 2fd commented
Awesome work! Thanks 😄

2021-11-19 18:32 UTC, merged