Suscribe to dao updates via email
decentraland/governance pull request #143
Opened 2021-11-29 22:23 UTC by jparnaudo

This PR addresses [this issue](https://www.notion.so/Suscribe-to-DAO-updates-via-email-4b18e748a0a043cf82dd701b7ac55815)

Banner only shows for logged users
![image](https://user-images.githubusercontent.com/2858950/143951609-97e00b75-6e5d-49f0-8e75-b09873a67e4f.png)

On every proposal category
![image](https://user-images.githubusercontent.com/2858950/143951644-b082d884-f6bb-4ac0-800a-a64ed2138a1e.png)

Looks like this
![image](https://user-images.githubusercontent.com/2858950/143951688-135c2697-1046-4b75-bb33-0e7dc30991b8.png)

Has local email format validation
![image](https://user-images.githubusercontent.com/2858950/143951718-5d988386-64d1-4bcc-8a3d-6e4947083778.png)

Displays mailchimp's format/data validation errors
![image](https://user-images.githubusercontent.com/2858950/143951780-bb75ad96-6478-4d65-ade0-60d816b3e3ec.png)

Shows success modal after successful subscription
![image](https://user-images.githubusercontent.com/2858950/143951830-4809207e-f9b6-46f4-bf02-374b0cb19fc3.png)

Saves subscribed user address in local storage. 

If we log out, banner does not appear
![image](https://user-images.githubusercontent.com/2858950/143952066-9cfa2b1d-0644-448a-9ef7-fbac77baff18.png)

If we log with another user, it shows again:
![image](https://user-images.githubusercontent.com/2858950/143952147-e126597f-1a39-468c-8c3f-f0666326e340.png)

2021-12-06 14:00 UTC, 2fd commented
Isn't that too intrusive for users. Cloud be at least add a close option and use `localStorage` to define if a user has subscribed or closed the banner and hide it?

2021-12-07 14:48 UTC, yemel commented
I have some comments on this:

* The newsletter should be visible always, not only for logged users.
* The header should be only visible on "All Proposals". If you filter by any category (POI, POLL, GRANT, etc) the newsletter header should be hidden.

Since it will be only visible at "All Proposals" it won't be too intrusive. I don't think we need a way to dismiss it.

2021-12-08 21:23 UTC, jparnaudo commented
Made the requested changes. 

Now the banner also shows for anonymous users (until they subscribe)

![til](https://imgflip.com/gif/5x51m3)

If a non subscripted user signs in, despite an anonymous user subscripted, banner for subscription shows:

![user1](https://kapwi.ng/c/OCLRxYeiWv)

If a different unsubscripted user logs in, banner shows again.  When subscribed, it disappears.

![user2](https://kapwi.ng/c/BBivt9fevr)

If there's no anonymous user subscribed, and subscribed user logs in, banner disappears. When user logs out, banner shows again.

![test3](https://kapwi.ng/c/3Ga2ep_wH8)

2021-12-17 17:53 UTC, 2fd requested changes

2021-12-17 17:53 UTC, 2fd commented on src/api/Governance.ts
> +  async subscribeToNewsletter(email: string) {
This featue shouldn't need and extra endpoint, can use the `/subscribe` endpoint directly

2021-12-17 17:53 UTC, 2fd commented on src/components/Modal/NewsletterSubscriptionModal.tsx
> +  const emailRegex = /\S+@\S+\.\S+/;
If you have a variable that never changes should be defined outside the component.

This case in particular it is preferred to use:
```ts
import isEmail from 'validator/lib/isEmail'
```

2021-12-17 17:53 UTC, 2fd commented on src/components/Modal/NewsletterSubscriptionModal.tsx
> +  function saveSubscription() {
use `useCallback`

2021-12-17 17:53 UTC, 2fd commented on src/components/Modal/NewsletterSubscriptionModal.tsx
> +  function resetModal() {
use  `useCallback`

2021-12-17 17:53 UTC, 2fd commented on src/components/Modal/NewsletterSubscriptionModal.tsx
> +      setEmail(email)
if you are setting more than one variable at same time a composite state is preferred:

```ts
const [ state, setState ] = useState<{ isValid, message, email }>({ isValid: true, message: '', email: ''})

// ...

setState({
  isValid: true,
  message: '',
  email: email
})
```

2021-12-17 17:53 UTC, 2fd commented on src/entities/NewsletterSubscription/routes.ts
> +  route.post('/newsletter/:email', handleAPI(subscribeToNewsletter))
plesae use the endpoint directly from the front end

2022-01-18 17:17 UTC, 2fd requested changes

2022-01-18 17:17 UTC, 2fd commented on src/api/Decentraland.ts
> +        .json({ email, interest: "dao"})
sorry guy, we need yo change this to: 

```suggestion
        .json({ email, list: "governance"})
```

2022-01-19 02:35 UTC, jparnaudo commented on src/api/Decentraland.ts
> +        .json({ email, interest: "dao"})
done!

2022-01-19 14:06 UTC, 2fd approved these changes

2022-01-19 14:06 UTC, merged