feat: add legislative tracker button
decentraland/governance pull request #1534
Opened 2024-01-11 12:37 UTC by andyesp

**Screenshots**
<img width="441" alt="image" src="https://github.com/decentraland/governance/assets/8242162/ddcceafe-ea76-4e38-b74c-7f5f82cd604e">

**Related Issue**
Closes #866 

- [ ]  **Functionality validation**
    - [ ]  Feature working as described in the related issue
    - [ ]  New environment variables have been set
    - [ ]  New API services methods have tests
    - [ ]  Code errors are being logged in the code health service
- [ ]  **Product validation**
    - [ ]  UI changes look the same as in Figma
    - [ ]  Usage events are being sent to the product analytics service
    - [ ]  New common components have been documented in Storybook
    - [ ]  Preview link if it’s a customer facing issue
- [ ] **Documentation**
    - [ ] README updated
    - [ ] New API changes are documented
- [ ] **Accessibility**
    - [ ] UI changes are accessible

2024-01-11 14:55 UTC, 1emu approved these changes

2024-01-13 11:44 UTC, ncomerci approved these changes

2024-01-15 14:22 UTC, 1emu approved these changes

2024-01-15 16:21 UTC, ginocingolani commented
@andyesp 
Check every binding Governance decision approved by the community on this living document maintained by the Facilitation Squad
CTA: Legislative Tracker

2024-01-15 16:30 UTC, ginocingolani requested changes
Copy proposed

2024-01-15 16:30 UTC, ginocingolani commented on src/intl/en.json
> +        "description": "Find all the binding outcomes from past DAO initiatives in this living document",
title: How do we govern?
body: Check the latest binding Governance decisions the community approved on this living document maintained by the Facilitation Squad
CTA: Legislative Tracker

2024-01-15 17:05 UTC, ginocingolani approved these changes
LGTM

2024-01-15 17:07 UTC, merged