Improves set up instructions
decentraland/governance pull request #239
Opened 2022-04-06 18:43 UTC by andresgalante

This PR slightly improves the instructions for setting up the projects by stating what are the requirements to run it.

2022-04-06 19:26 UTC, ncomerci approved these changes

2022-04-06 20:45 UTC, andyesp requested changes

2022-04-06 20:45 UTC, andyesp commented on README.md
> +- [NodeJS](https://www.npmjs.com/) that includes `npm`
This should be the [Node.js url](https://nodejs.org/).

2022-04-08 14:10 UTC, andresgalante commented
Conflict resolved

2022-04-11 17:24 UTC, 1emu approved these changes

2022-04-11 19:36 UTC, andyesp approved these changes

2022-04-11 19:36 UTC, andyesp approved these changes
Thanks for your contribution ✨

2022-04-13 14:20 UTC, merged